# version: '3.8'
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ~/.aws:/home/nonroot/.aws:cached
      - ~/.ssh:/home/nonroot/.ssh:cached
      - ~/.gitconfig:/home/nonroot/.gitconfig:cached
      - /var/run/docker.sock:/var/run/docker.sock:cached
